# Generated by Django 4.0.6 on 2022-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
    ]
