# Generated by Django 4.0.6 on 2022-12-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usercourse_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=200)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('due_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('lowest_grade', models.CharField(max_length=20)),
                ('highest_grade', models.CharField(max_length=20)),
                ('passing_grade', models.CharField(max_length=20)),
                ('inverted_scale', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
    ]
