# Generated by Django 4.0.6 on 2022-12-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_todo_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_starred',
            new_name='is_flagged',
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='erasmus_user', to='accounts.erasmususer'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
