# Generated by Django 4.0.6 on 2022-12-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_is_starred_todo_is_flagged_todo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
