# Generated by Django 4.0.6 on 2022-12-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_todo_body_alter_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmususer',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.coordinator'),
        ),
    ]
