# Generated by Django 4.0.6 on 2022-12-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_todo_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='takenInsteadOf',
        ),
    ]
