# Generated by Django 4.0.6 on 2022-12-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_usercourse_takeninsteadof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
