# Generated by Django 4.0.6 on 2022-12-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmususer',
            name='department',
            field=models.CharField(default='Computer Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='', max_length=20),
        ),
    ]
