# Generated by Django 4.0.6 on 2022-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
