# Generated by Django 4.0.6 on 2022-12-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_elective_group_name_alter_course_course_type_and_more'),
        ('accounts', '0012_alter_usercourse_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmususer',
            name='department',
            field=models.CharField(default='Computer Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.university'),
        ),
    ]
