# Generated by Django 4.0.6 on 2022-12-16 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_erasmususer_department_student_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.coordinator'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='erasmus', to='accounts.erasmususer'),
        ),
    ]
