# Generated by Django 4.0.6 on 2022-12-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_document_document_alter_document_document_type'),
        ('accounts', '0014_student_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.university'),
        ),
    ]
