# Generated by Django 4.0.6 on 2022-12-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_coordinator_user_alter_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmususer',
            name='phone',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
