# Generated by Django 4.0.6 on 2022-12-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_erasmususer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmususer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
