# Generated by Django 4.0.6 on 2022-12-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_erasmususer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobility_visiblity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
