# Generated by Django 4.0.6 on 2022-12-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_student_email_visibility_student_mobility_visiblity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='final_list_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Account created', 'Account created'), ('Placement done', 'Placement done'), ('No placement', 'No placement'), ('Choosing courses', 'Choosing courses'), ('Waiting for the course approval', 'Waiting for the course approval'), ('Waiting for the final course list approval', 'Waiting for the final course list approval'), ('Waiting for the pre-approval form to be signed', 'Waiting for the pre-approval form to be signed'), ('In mobility period', 'In mobility period'), ('Finished mobility period', 'Finished mobility period')], default='Account created', max_length=200),
        ),
    ]
