# Generated by Django 4.0.6 on 2022-12-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_student_final_list_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmususer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
