# Generated by Django 4.0.6 on 2022-12-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_faq', models.BooleanField(default=True, editable=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
