# Generated by Django 4.0.6 on 2022-12-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_todo_university'),
        ('communication', '0002_faq_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('faq', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_singleton', to='communication.faq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='accounts.coordinator')),
            ],
        ),
    ]
