# Generated by Django 4.1.4 on 2022-12-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_university'),
        ('communication', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_flagged', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to='accounts.erasmususer')),
            ],
        ),
    ]
