# Generated by Django 4.0.6 on 2022-12-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_forum', models.BooleanField(default=True, editable=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
