# Generated by Django 4.0.6 on 2022-12-17 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_post_alter_question_user_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_singleton', to='communication.forum'),
        ),
    ]
