# Generated by Django 4.0.6 on 2022-12-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_alter_post_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
