# Generated by Django 4.0.6 on 2022-12-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_codes', models.CharField(max_length=20)),
                ('course_credit', models.FloatField()),
                ('approved', models.BooleanField(default=False)),
                ('grade', models.CharField(max_length=20)),
                ('courseType', models.CharField(max_length=30)),
                ('course_coordinator_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
