# Generated by Django 4.0.6 on 2022-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_grade'),
    ]

