# Generated by Django 4.0.6 on 2022-12-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_erasmususer_department_student_academic_year_and_more'),
        ('courses', '0004_university_rename_coursetype_course_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='elective_group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Learning Agreement', 'Learning Agreement'), ('Preapproval Form', 'PreApproval Form'), ('Course Transfer Form', 'Course Transfer Form'), ('Other', 'Other')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Must', 'Must'), ('Elective', 'Elective')], max_length=30),
        ),
    ]
