# Generated by Django 4.0.6 on 2022-12-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_university'),
        ('courses', '0004_university_rename_coursetype_course_course_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='static/documents/documents/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('Learning Agreement', 'Learning Agreement'), ('Preapproval Form', 'PreApproval Form'), ('Course Transfer Form', 'Course Transfer Form'), ('Other', 'Other')], default=4, max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents_user', to='accounts.student')),
            ],
        ),
    ]
