# Generated by Django 4.0.6 on 2022-12-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_elective_group_name_document_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='static/documents/documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Learning Agreement', 'Learning Agreement'), ('Pre-Approval Form', 'Pre-Approval Form'), ('Course Transfer Form', 'Course Transfer Form'), ('Other', 'Other')], default='1', max_length=20),
        ),
    ]
