# Generated by Django 4.0.6 on 2022-12-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='elective_group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Must', 'Must'), ('Elective', 'Elective')], max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Learning Agreement', 'Learning Agreement'), ('Pre-Approval Form', 'Pre-Approval Form'), ('Course Transfer Form', 'Course Transfer Form'), ('Other', 'Other')], default=4, max_length=20),
        ),
    ]
