# Generated by Django 4.0.6 on 2022-12-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Learning Agreement', 'Learning Agreement'), ('Preapproval Form', 'PreApproval Form'), ('Course Transfer Form', 'Course Transfer Form'), ('Other', 'Other')], default=4, max_length=20),
        ),
    ]
