# Generated by Django 4.0.6 on 2022-12-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_coordinator_user_alter_student_user_and_more'),
        ('courses', '0006_course_elective_group_name_alter_course_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.university'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.student'),
        ),
    ]
