# Generated by Django 4.0.6 on 2022-12-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_university_alter_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
