# Generated by Django 4.0.6 on 2022-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilkentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20)),
                ('course_credit', models.FloatField()),
                ('course_type', models.CharField(choices=[('Must', 'Must'), ('Elective', 'Elective')], max_length=30)),
                ('elective_group_name', models.CharField(blank=True, max_length=100)),
                ('course_coordinator_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
