# Generated by Django 4.0.6 on 2022-12-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_bilkentcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_coordinator_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='elective_group_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='bilkent_equivalent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.bilkentcourse'),
        ),
    ]
