# Generated by Django 4.0.6 on 2022-12-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_course_coordinator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
