# Generated by Django 4.0.6 on 2022-12-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergedcourse',
            name='course_type',
        ),
        migrations.AlterField(
            model_name='mergedcourse',
            name='bilkent_equivalent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.bilkentcourse'),
        ),
    ]
