# Generated by Django 4.0.6 on 2022-12-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_bilkent_equivalent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilkentcourse',
            name='course_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
