# Generated by Django 4.0.6 on 2022-12-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_bilkentcourse_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilkentcourse',
            name='course_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
