# Generated by Django 4.0.6 on 2022-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_bilkentcourse_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_signed_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
