# Generated by Django 4.0.6 on 2022-12-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_document_is_signed_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedcourse',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mergedcourse',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
