# Generated by Django 4.0.6 on 2022-12-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_mergedcourse_approved_mergedcourse_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
