# Generated by Django 4.0.6 on 2022-12-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedcourse',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
