# Generated by Django 4.0.6 on 2022-12-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_mergedcourse_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
