# Generated by Django 4.0.6 on 2022-12-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
